# Generated by Django 5.1.6 on 2025-02-25 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (must be unique within company)', max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Department Name')),
                ('company', models.ForeignKey(help_text='Company for this department', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Department',
                'unique_together': {('name', 'company')},
            },
        ),
    ]
