# Generated by Django 5.1.6 on 2025-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number_of_departments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_employees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
