# Generated by Django 5.1.6 on 2025-03-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_number_of_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='number_of_departments',
        ),
        migrations.RemoveField(
            model_name='company',
            name='number_of_employees',
        ),
    ]
