# Generated by Django 5.1.6 on 2025-02-25 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('mobile_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^(?:\\+20|0)1[0125]\\d{8}$')], verbose_name='Mobile Number')),
                ('address', models.TextField(null=True, verbose_name='Full Address')),
                ('designation', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Job Title')),
                ('status', models.CharField(choices=[('application_received', 'Application Received'), ('interview_scheduled', 'Interview Scheduled'), ('hired', 'Hired'), ('not_accepted', 'Not Accepted')], default='application_received', max_length=20, verbose_name='Employment Status')),
                ('hired_on', models.DateField(verbose_name='Hire Date')),
                ('days_employed', models.PositiveIntegerField(editable=False, verbose_name='Days Employed')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='department.department', verbose_name='Department')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee',
            },
        ),
    ]
